export const FETCHING_PUBLIC_PROFILE = 'FETCHING_PUBLIC_PROFILE'
export const FETCHED_PUBLIC_PROFILE_SUCCESS = 'FETCHED_PUBLIC_PROFILE_SUCCESS'
export const FETCHED_PUBLIC_PROFILE_ERROR = 'FETCHED_PUBLIC_PROFILE_ERROR'
