export const FETCHING_PUBLIC_PROFILE = 'FETCHING_PUBLIC_PROFILE'
export const FETCHED_PUBLIC_PROFILE_SUCCESS = 'FETCHED_PUBLIC_PROFILE_SUCCESS'
export const FETCHED_PUBLIC_PROFILE_ERROR = 'FETCHED_PUBLIC_PROFILE_ERROR'

export const REQUESTED_PROFILE_UNLOCK = 'REQUESTED_PROFILE_UNLOCK'
export const PROFILE_UNLOCK_SUCCESS = 'PROFILE_UNLOCK_SUCCESS'
export const PROFILE_UNLOCK_FAILURE = 'PROFILE_UNLOCK_FAILURE'

export const REQUEST_EDIT_PROFILE = 'REQUEST_EDIT_PROFILE'
export const EDIT_FIELD = 'EDIT_FIELD'
